# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip_id',
            field=models.IntegerField(default=1, verbose_name='用户对应的会员'),
        ),
    ]
