# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='level',
            field=models.IntegerField(default=0, unique=True, verbose_name='会员等级'),
        ),
    ]
